cliniskills/cliniskills/urls.py
# General Imports
from django.contrib import admin
from django.urls import path, include

# For Media Setup
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('lecture/', include('lecture.urls')),
    path('note/', include('note.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cliniskills/home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns=[
    path('', views.index, name='index'),
    path('services', views.services, name='services'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('login', views.custom_login, name='login'),
    path('password_reset', views.password_reset, name='password_reset'),
    path('new_password', views.new_password, name='new_password'),
    path('signup', views.signup, name='signup'),
    path('logout/', views.logout_request, name='logout'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/request_delete_profile/', views.request_delete_profile, name='request_delete_profile'),
    path('payment-success/', views.payment_success, name='payment_success'),

]

cliniskills/lecture/urls.py
from django.urls import path
from . import views

app_name='lecture'

urlpatterns=[
    path('', views.index, name='index'),
]

cliniskills/note/urls.py
from django.urls import path
from . import views

app_name='note'

urlpatterns=[
    path('', views.index, name='index'),
]

cliniskills/home/models.py
from django.db.models.signals import post_save
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.dispatch import receiver

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Additional fields for user profile
    bio = models.TextField(max_length=500, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.user.username

class Subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField(default=timezone.now)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.user.username}'s Subscription"

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    date = models.DateField(default=timezone.now)
    # Additional payment related information
    transaction_id = models.CharField(max_length=100)

    def __str__(self):
        return f"Payment by {self.user.username} on {self.date}"


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.get_or_create(user=instance)  # changed to get_or_create
    else:
        instance.userprofile.save()

cliniskills/home/forms.py
from django import forms
from django.contrib.auth.models import User

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email'] 

cliniskills/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from razorpay_custom_secret_keys import *
from .models import *
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    user = request.user
    is_subscription_active = False

    if user.is_authenticated:
        try:
            subscription = Subscription.objects.get(user=user)
            is_subscription_active = subscription.is_active
        except Subscription.DoesNotExist:
            pass
    context={
        'is_subscription_active': is_subscription_active
    }
    return render(request, 'home/index.html', context)

def custom_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home:index')  # Redirect to the home page or any other page
        else:
            # Return an 'invalid login' error message
            return render(request, 'home/login.html', {'error': 'Invalid username or password.'})
    else:
        return render(request, 'home/login.html')

def logout_request(request):
    logout(request)
    return redirect('home:index')  # Redirect to the home page or any other page after logout

def password_reset(request):
    return render(request, 'home/password_reset.html')

def new_password(request):
    return render(request, 'home/new_password.html')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists', extra_tags='bg-red-100 text-red-700 border border-red-400')
                return redirect('home:signup')
            elif User.objects.filter(email=email).exists():
                messages.error(request, 'Email already registered', extra_tags='bg-red-100 text-red-700 border border-red-400')
                return redirect('home:signup')
            else:
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save()
                login(request, user)
                messages.success(request, 'Account created successfully', extra_tags='bg-green-100 text-green-700 border border-green-400')
                return redirect('home:index')
        else:
            messages.error(request, 'Passwords do not match', extra_tags='bg-red-100 text-red-700 border border-red-400')
            return redirect('home:signup')

    else:
        return render(request, 'home/signup.html')

def services(request):
    context = {
        'razorpay_key_id': RAZORPAY_KEY_ID
    }
    return render(request, 'home/services.html', context)

def about(request):
    return render(request, 'home/about.html')

def contact(request):
    return render(request, 'home/contact.html')

@login_required
def view_profile(request):
    user = get_object_or_404(User, username=request.user.username)
    user_subscription = None
    if request.user.is_authenticated:
        user_subscription = Subscription.objects.filter(user=request.user).first()
    return render(request, 'home/view_profile.html', {'user': user, 'user_subscription': user_subscription})

@login_required
def request_delete_profile(request):
    if request.method == 'POST':
        # Logic to handle deletion request
        messages.success(request, 'Your profile deletion request has been sent to the admin.', extra_tags='bg-green-100 text-green-700 border border-green-400')
        return redirect('home:view_profile')

    # Redirect to profile or other appropriate page if not POST
    return redirect('home:view_profile')

@login_required
@csrf_exempt  # Necessary for handling POST requests from Razorpay
def payment_success(request):
    if request.method == 'POST':
        # Extract payment details from request.POST
        razorpay_payment_id = request.POST.get('razorpay_payment_id')
        razorpay_order_id = request.POST.get('razorpay_order_id')
        user = request.user
        amount = 1000  # Set this to the actual amount

        # Verify payment (You should verify the signature here as per Razorpay docs)

        # Create or update the payment record
        Payment.objects.create(
            user=user,
            amount=amount,
            date=timezone.now(),
            transaction_id=razorpay_payment_id
        )

        # Update or create the subscription
        subscription, created = Subscription.objects.get_or_create(user=user)
        subscription.start_date = timezone.now()
        subscription.is_active = True
        subscription.save()

        messages.success(request, 'Payment successful!')
        return render(request, 'home/payment_success.html')

    # Handle non-POST requests or failed verifications
    messages.error(request, 'Payment failed.')
    return render(request, 'home/payment_failure.html')

cliniskills/home/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CliniProsper</title>
    <!-- Tailwind CSS CDN -->
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="shortcut icon" href="{% static 'home/images/favicon.ico' %}" type="image/x-icon">
</head>

<body class="flex flex-col min-h-screen bg-gray-100 text-gray-800">

    <nav class="bg-white shadow-lg">
        <div class="max-w-6xl mx-auto px-4">
            <div class="flex justify-between items-center">
                <!-- Website Logo -->
                <a href="{% url 'home:index' %}" class="flex items-center py-4 px-2">
                    <span class="font-semibold text-gray-500 text-lg">CliniProsper</span>
                </a>

                <!-- Hamburger Menu for smaller screens -->
                <div class="md:hidden">
                    <button class="outline-none mobile-menu-button">
                        <svg class="w-6 h-6 text-gray-500 hover:text-green-500"
                            fill="none"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path d="M4 6h16M4 12h16m-7 6h7"></path>
                        </svg>
                    </button>
                </div>

                <!-- Primary Navbar items for Desktop -->
                <div class="hidden md:flex items-center space-x-3">
                    <!-- Conditional Links for Authenticated Users -->
                    <a href="{% url 'home:index' %}" class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-green-500 hover:text-white transition duration-300 {% if path == '/' %}border-b-4 border-green-500 text-green-500{% endif %}">Home</a>
                    <a href="{% url 'home:services' %}" class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-green-500 hover:text-white transition duration-300 {% if path == '/services' %}border-b-4 border-green-500 text-green-500{% endif %}">Services</a>
                    <a href="{% url 'home:about' %}" class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-green-500 hover:text-white transition duration-300 {% if path == '/about' %}border-b-4 border-green-500 text-green-500{% endif %}">About</a>
                    <a href="{% url 'home:contact' %}" class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-green-500 hover:text-white transition duration-300 {% if path == '/contact' %}border-b-4 border-green-500 text-green-500{% endif %}">Contact</a>
                    {% if user.is_authenticated %}
                    {% if is_subscription_active %}
                        <!-- Links to Lectures and Notes -->
                        <a href="{% url 'lecture:index' %}" class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-green-500 hover:text-white transition duration-300 {% if path == '/lectures' %}border-b-4 border-green-500 text-green-500{% endif %}">Lectures</a>
                        <a href="{% url 'note:index' %}" class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-green-500 hover:text-white transition duration-300 {% if path == '/notes' %}border-b-4 border-green-500 text-green-500{% endif %}">Notes</a>
                    {% endif %}
                    <a href="{% url 'home:view_profile' %}" class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-green-500 hover:text-white transition duration-300">Profile</a>
                    <a href="{% url 'home:logout' %}" class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-green-500 hover:text-white transition duration-300">Logout</a>
                    {% else %}
                    <a href="{% url 'home:login' %}" class="py-2 px-2 font-medium text-gray-500 rounded hover:bg-green-500 hover:text-white transition duration-300 {% if path == '/login' %}border-b-4 border-green-500 text-green-500{% endif %}">Log In</a>
                    <a href="{% url 'home:signup' %}" class="py-2 px-2 font-medium text-white bg-green-500 rounded hover:bg-green-400 transition duration-300 {% if path == '/signup' %}border-b-4 border-green-500 text-green-500{% endif %}">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- Mobile Menu for smaller screens -->
        <div class="mobile-menu hidden md:hidden">
            <!-- Mobile Navigation Links Here -->
            <a href="{% url 'home:index' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300 {% if path == '/' %}border-b-4 border-green-500 text-green-500{% endif %}">Home</a>
            <a href="{% url 'home:services' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300 {% if path == '/services' %}border-b-4 border-green-500 text-green-500{% endif %}">Services</a>
            <a href="{% url 'home:about' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300 {% if path == '/about' %}border-b-4 border-green-500 text-green-500{% endif %}">About</a>
            <a href="{% url 'home:contact' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300 {% if path == '/contact' %}border-b-4 border-green-500 text-green-500{% endif %}">Contact</a>

            <!-- Conditional Links for Authenticated Users -->
            {% if user.is_authenticated %}
            {% if is_subscription_active %}
                <!-- Links to Lectures and Notes -->
                <a href="{% url 'lecture:index' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300 {% if path == '/lectures' %}border-b-4 border-green-500 text-green-500{% endif %}">Lectures</a>
                <a href="{% url 'note:index' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300 {% if path == '/notes' %}border-b-4 border-green-500 text-green-500{% endif %}">Notes</a>
            {% endif %}            
            <a href="{% url 'home:view_profile' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300 {% if path == '/profile' %}border-b-4 border-green-500 text-green-500{% endif %}">Profile</a>
            <a href="{% url 'home:logout' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300">Logout</a>
            {% else %}
            <a href="{% url 'home:login' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300 {% if path == '/login' %}border-b-4 border-green-500 text-green-500{% endif %}">Log In</a>
            <a href="{% url 'home:signup' %}" class="block py-2 px-2 text-sm text-gray-500 font-semibold hover:text-green-500 transition duration-300 {% if path == '/signup' %}border-b-4 border-green-500 text-green-500{% endif %}">Sign Up</a>
            {% endif %}
        </div>
    </nav>

    <!-- Main Content -->
    <div class="flex-grow mb-4">
        {% block content %}
        <!-- Content will go here -->
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="bg-white shadow-lg p-4 text-center">
        <span class="text-sm text-gray-500 sm:text-center">© 2023 CliniProsper. All Rights Reserved.</span>
        <br>
        <span class="text-sm text-gray-500 sm:text-center">Created by <a href="https://www.linkedin.com/in/divyesh-vishwakarma-621197175/">Divyesh Vishwakarma</a></span>
    </footer>

    <!-- Mobile Menu Javascript -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const mobileMenuButton = document.querySelector('.mobile-menu-button');
            const mobileMenu = document.querySelector('.mobile-menu');

            mobileMenuButton.addEventListener('click', function () {
                mobileMenu.classList.toggle('hidden');
            });
        });
    </script>
    {% block extra_js %}
    {% endblock %}
</body>
</html>